name: Deploy Static Site to Render

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the GitHub repository
        uses: actions/checkout@v4

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.STAGING_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_TOKEN }}
          wait_deploy: true
